"use strict";class Anura{version={semantic:{major:"1",minor:"0",patch:"0",},buildstate:"alpha",codename:"Lag Train",get pretty(){const semantic=anura.version.semantic;return `${semantic.major}.${semantic.minor}.${semantic.patch} ${anura.version.buildstate}`;},};initComplete=false;x86;settings;fs;config;notifications;x86hdd;constructor(fs,settings,config,hdd){this.fs=fs;this.settings=settings;this.config=config;this.x86hdd=hdd;this.notifications=new NotificationService();document.body.appendChild(this.notifications.element);}
static async new(config){const fs=new Filer.FileSystem({name:"anura-mainContext",provider:new Filer.FileSystem.providers.IndexedDB(),});fs.readFileSync=async(path)=>{return await new Promise((resolve,reject)=>{return fs.readFile(path,function async(err,data){resolve(new TextDecoder("utf8").decode(data));});});};const settings=await Settings.new(fs,config.defaultsettings);const hdd=await InitV86Hdd();const anuraPartial=new Anura(fs,settings,config,hdd);return anuraPartial;}
wm=new WMAPI();apps={};logger={log:console.log.bind(console,"anuraOS:"),debug:console.debug.bind(console,"anuraOS:"),warn:console.warn.bind(console,"anuraOS:"),error:console.error.bind(console,"anuraOS:"),};async registerApp(app){if(app.package in this.apps){throw "Application already installed";}
launcher.addShortcut(app);taskbar.addShortcut(app);this.apps[app.package]=app;if(this.initComplete){taskbar.updateTaskbar();alttab.update();}
return app;}
async registerExternalApp(source){const resp=await fetch(`${source}/manifest.json`);const manifest=await resp.json();const app=new ExternalApp(manifest,source);await anura.registerApp(app);return app;}
ContextMenu=ContextMenuAPI;removeStaleApps(){for(const appName in anura.apps){const app=anura.apps[appName];app.windows.forEach((win)=>{if(!win.element.parentElement){app.windows.splice(app.windows.indexOf(win));}});}
taskbar.updateTaskbar();alttab.update();}
files=new FilesAPI();async python(appname){return await new Promise((resolve,reject)=>{const iframe=document.createElement("iframe");iframe.setAttribute("style","display: none");iframe.setAttribute("src","/apps/python.app/lib.html");iframe.id=appname;iframe.onload=async function(){console.log("Called from python");const pythonInterpreter=await document.getElementById(appname).contentWindow.loadPyodide({stdin:()=>{const result=prompt();echo(result);return result;},});pythonInterpreter.globals.set("AliceWM",AliceWM);pythonInterpreter.globals.set("anura",anura);pythonInterpreter.window=(document.getElementById(appname)).contentWindow;resolve(pythonInterpreter);};document.body.appendChild(iframe);});}
get wsproxyURL(){return this.settings.get("wsproxy-url");}}